apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.82.0
    helm:
      realeasName: kiali
    values: |
      auth:
        strategy: "anonymous"
      deployment:
        ingress_enabled: true
      external_services:
        istio:
          root_namespace: istio-system
        prometheus:
          url: "http://prometheus-server.prometheus-system:80"
      istio_namespace: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 